### ISSUE TITLE
nimbleHMC() failed

### ISSUE THREAD

**Issue by yangchino1** [nimble-dev/nimbleHMC#11]
Hi,
I installed the AD-beta version of *nimble*, and the *nimbleHMC* package following the instruction. I tested the function `nimbleHMC()` by running `example(numbleHMC,run.dontrun=T)`, then I got the following message

> nmbHMC> code <- nimbleCode({
nmbHMC+     mu ~ dnorm(0, sd = 1000)
nmbHMC+     sigma ~ dunif(0, 1000)
nmbHMC+     for(i in 1:10) {
nmbHMC+         x[i] ~ dnorm(mu, sd = sigma)
nmbHMC+     }
nmbHMC+ })
>
> nmbHMC> data <- list(x = c(2, 5, 3, 4, 1, 0, 1, 3, 5, 3))
>
> nmbHMC> inits <- function() list(mu = rnorm(1,0,1), sigma = runif(1,0,10))
>
> nmbHMC> mcmc.output <- nimbleHMC(code, data = data, inits = inits,
nmbHMC+                          monitors = c("mu", "sigma"), thin = 10,
nmbHMC+                          niter = 20000, nburnin = 1000, nchains = 3,
nmbHMC+                          summary = TRUE, WAIC = TRUE)
Error in mcmc_createModelObject(code, constants, data, inits, dimensions,  : 
  could not find function "mcmc_createModelObject"

**Comment by danielturek** [comment]
@yangchino1 Sorry about that, there was an issue with exporting the right function name from the `nimble` package.

Can you try re-installing *both* `nimble` and `nimbleHMC`, following the instructions on the `nimbleHMC` README page?

Then try running the example again, and let me know if it works.

**Comment by yangchino1** [comment]
OK, it works for R 4.2.1 on Win10 with the following output
> example(nimbleHMC,run.dontrun=T)
>
> nmbHMC> code <- nimbleCode({
nmbHMC+     mu ~ dnorm(0, sd = 1000)
nmbHMC+     sigma ~ dunif(0, 1000)
nmbHMC+     for(i in 1:10) {
nmbHMC+         x[i] ~ dnorm(mu, sd = sigma)
nmbHMC+     }
nmbHMC+ })
>
>nmbHMC> data <- list(x = c(2, 5, 3, 4, 1, 0, 1, 3, 5, 3))
>
>nmbHMC> inits <- function() list(mu = rnorm(1,0,1), sigma = runif(1,0,10))
>
>nmbHMC> mcmc.output <- nimbleHMC(code, data = data, inits = inits,
nmbHMC+                          monitors = c("mu", "sigma"), thin = 10,
nmbHMC+                          niter = 20000, nburnin = 1000, nchains = 3,
nmbHMC+                          summary = TRUE, WAIC = TRUE)
Defining model
Building model
Setting data and initial values
Running calculate on model
  [Note] Any error reports that follow may simply reflect missing values in model variables.
Checking model sizes and dimensions
Checking model calculations
Compiling
  [Note] This may take a minute.
  [Note] Use 'showCompilerOutput = TRUE' to see C++ compilation details.
running chain 1 ...
  [Note] HMC sampler (nodes: mu, sigma) is using 1000 warmup iterations
|-------------|-------------|-------------|-------------|
|-------------------------------------------------------|
  [Note] HMC sampler (nodes: mu, sigma) encountered 17 divergent paths
  [Note] HMC sampler (nodes: mu, sigma) reached the maximum search tree depth 1 time
running chain 2 ...
  [Note] HMC sampler (nodes: mu, sigma) is using 1000 warmup iterations
|-------------|-------------|-------------|-------------|
|-------------------------------------------------------|
  [Note] HMC sampler (nodes: mu, sigma) encountered 18 divergent paths
running chain 3 ...
  [Note] HMC sampler (nodes: mu, sigma) is using 1000 warmup iterations
|-------------|-------------|-------------|-------------|
|-------------------------------------------------------|
  [Note] HMC sampler (nodes: mu, sigma) encountered 14 divergent paths
