### ISSUE TITLE
add/update COPYRIGHTS and LICENSE

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#15]
I'm inclined to follow how we have `LICENSE` and `COPYRIGHTS` in the nimble package. @danielturek let me know if you have thoughts, but I'm happy to just make that change.

**Comment by danielturek** [comment]
@paciorek I'm fine with this, and making the addition.  What would you think about:

In `nimbleHMC/inst/COPYRIGHTS`:
```
Files: R/*
Copyright: Copyright (C) 2023 the NIMBLE authors.
License: GPL-3.0
```

and in `nimbleHMC/LICENSE`:
```
YEAR: 2023
COPYRIGHT HOLDER: Perry de Valpine, Christopher Paciorek, Daniel Turek
ORGANIZATION: University of California
```

Is this along the lines of what you were thinking?  Please suggest any changes.

**Comment by paciorek** [comment]
Yes, except we've been using BSD in `COPYRIGHTS`:

```
License: BSD_3_clause
```

**Comment by danielturek** [comment]
@paciorek Please take a look at `master` branch of `nimbleHMC`.

**Comment by paciorek** [comment]
LGTM
