### ISSUE TITLE
avoid `expect_error(foo, NA)`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#16]
I'd like to avoid this kind of use of `expect_error`. There is an `expect_no_error` or simply having the code not in an `expect_`, in which case an error will cause testthat to report the error.

@danielturek I can change, but wanted to run by you first in case I'm not understanding what you're doing here.

**Comment by danielturek** [comment]
@paciorek No, you're right, using `expect_no_error` seems cleaner.  I'll take a look at this.

**Comment by danielturek** [comment]
@paciorek Fixed on `master` branch of `nimbleHMC`
