### ISSUE TITLE
include `methods` in `NAMESPACE`?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#18]
@danielturek I see you took `import(methods)` out of `NAMESPACE` but left it in `DESCRIPTION`. 

However, it needs to be in both or `R CMD check` reports: `Namespace in Imports field not imported from: ‘methods’`.

I'm putting it back into `NAMESPACE` -- please let me know if you have concerns.

**Comment by danielturek** [comment]
@paciorek Sounds good, thank you.
