### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by kabarigou** [nimble-dev/nimbleHMC#19]
I am trying to install nimbleHMC using the following script: 
```R
library(devtools)
install_github("nimble-dev/nimble", ref = "AD-rc0", subdir = "packages/nimble")
install_github("nimble-dev/nimbleHMC", subdir = "nimbleHMC")
````
The installation of nimble runs fine but I can't install nimbleHMC because `package 'nimble' 0.13.1 was found, but >= 1.0.0 is required by 'nimbleHMC'`, however there is no version 1.0.0 of nimble ?

Full error script: 
```R
remotes::install_github("nimble-dev/nimbleHMC", subdir = "nimbleHMC")
Downloading GitHub repo nimble-dev/nimbleHMC@HEAD
Running `R CMD build`...
* checking for file 'C:\Users\kabar\AppData\Local\Temp\Rtmpcxcn6x\remotes2d7429b6bd\nimble-dev-nimbleHMC-4c6a703\nimbleHMC/DESCRIPTION' ... OK
* preparing 'nimbleHMC':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
Omitted 'LazyData' from DESCRIPTION
* building 'nimbleHMC_0.1.0.tar.gz'
Installing package into ‘C:/Users/kabar/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'nimbleHMC' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: package 'nimble' 0.13.1 was found, but >= 1.0.0 is required by 'nimbleHMC'
Execution halted
ERROR: lazy loading failed for package 'nimbleHMC'
* removing 'C:/Users/kabar/AppData/Local/R/win-library/4.2/nimbleHMC'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/kabar/AppData/Local/Temp/Rtmpcxcn6x/file2d746f091c22/nimbleHMC_0.1.0.tar.gz’ had non-zero exit status
```

Thanks for your help !

**Comment by paciorek** [comment]
Sorry about that -- we've been making updates to `nimbleHMC` in preparation for the release, and that work in progress has some crossed wires in terms of the version of `nimble` it needs.

 We should have set a stable branch for users to install from. I've done that now. Please try:

```
remotes::install_github("nimble-dev/nimbleHMC", ref="AD-rc1", subdir = "nimbleHMC")
```
Windows users might need to include an additional argument to install nimbleHMC:
```
remotes::install_github("nimble-dev/nimbleHMC", ref="AD-rc1", subdir = "nimbleHMC", INSTALL_opts = "--no-multiarch")
```

**Comment by kabarigou** [comment]
Thank you very much, it works !

**Comment by danielturek** [comment]
@paciorek @kabarigou The installation instructions for `nimbleHMC` on the [package README page](https://github.com/nimble-dev/nimbleHMC) are now updated to reflect this.

My apologies this content was out-of-date.

**Comment by paciorek** [comment]
I had updated the instructions at `r-nimble.org/ad-beta`. Those indicate to use the `AD-rc1` branch of **nimbleHMC**, so I think we want that in the README too -- I'm not actually seeing any updates in the package README -- did you push?

**Comment by danielturek** [comment]
@paciorek Thanks, nice eye.  Pushed now.
