### ISSUE TITLE
trapping discrete nodes

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#20]
We currently trap discrete nodes in the parameter transform system:

```
Error in parameterTransform(model, targetNodesAsScalars) : 
  parameterTransform nodes may not be discrete: y2
```

- I think we should say "cannot" as "may not" could be read as "might not".
- Do we want to augment the message in some way to indicate that HMC cannot be run on discrete parameters? I'm glad we are catching this, but the fact that it occurs in the param transform context feels somewhat indirect (though perhaps one can argue that mathematically it is the inability to tranform to R^d that is the problem) and reporting it this way may confuse users.

@danielturek @perrydv thoughts?

@perrydv this relates to our discussion of whether we trap latent nodes being discrete.

**Comment by danielturek** [comment]
@paciorek I'm fine with any change in the language as you suggested.  Perhaps
```
parameterTransform cannot operate on discrete-valued nodes: NODES
```

Also, my take on the "where the error occurs" question: Maybe just adding a line or two into the HMC sampler setup code:
```
if(any input nodes are discrete)
   give an informative error (with node names) from inside the HMC sampler
```
And also leaving the check in the `parameterTransform`, for other applications of it.
Does this sound reasonable?
I certainly welcome other thoughts or ideas.

**Comment by paciorek** [comment]
Thanks - I hadn't thought things through -- adding a line in HMC setup sounds great to me. LMK if you want to do it or I should.

**Comment by danielturek** [comment]
@paciorek I just:

- Updated the error messages in `parameterTransform` setup code, on branch `ADoak`.
- Added error trap for discrete nodes in `HMC` sampler setup code

These changes are pushed.

**Comment by paciorek** [comment]
Great, thanks. I'm adding a test of the error trap.
