### ISSUE TITLE
use of `--no-multiarch` and `--merge-multiarch`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#24]
I think we decided that the Windows binary needs to be built with `--merge-multiarch`. We need to tell CRAN this in the optional notes field when we submit, as we do for `nimble` itself.

I don't remember all the reasoning for this and am a bit confused because no compilation is done to install nimbleHMC; we just create a couple nimbleFunctions. @danielturek @perrydv do either of you remember?

**Comment by danielturek** [comment]
@paciorek I don't remember any specifics about this, but one option is to leave it as-is for now, and if Windows binary fails at the time of CRAN submission, then address this for `nimbleHMC`.

Does that sound ok?  But I'm open to suggestions here.

**Comment by paciorek** [comment]
I think we would only know that it doesn't work for users on Windows at the point that users start to try to use the nimbleHMC binary on CRAN. 

I think we can test this in advance since Perry and Paul have Windows machines. So we can build the binary with and without this and see how it works on a different machine.

**Comment by danielturek** [comment]
Sounds like a good plan.

@paul-vdb or @perrydv Are either of you up for trying this, using the current `master` branch of `nimbleHMC` ?

**Comment by paciorek** [comment]
To make a specific suggestion, perhaps @perrydv can build nimbleHMC binaries both with and without that flag and then send them to @paul-vdb who could run the test code.

We probably want to wait until the nimble 1.0.0 binary is available from CRAN so that @paul-vdb can try this using the official nimble 1.0.0 that users would have.

**Comment by paciorek** [comment]
Looks like the Windows 1.0.0 binary is up on CRAN.

**Comment by perrydv** [comment]
Yes @paciorek @danielturek @paul-vdb I can build these Windows binaries and share with Paul. Sorry I do not seem to have notifications from this repo through my slack system for following GitHub. I will set that up later.

**Comment by perrydv** [comment]
FWIW, here is what the R-admin manual says:

```
For almost all packages R CMD INSTALL will attempt to install both 32- and 64-bit builds of a package if run from a 32/64-bit install of R (only 64-bit builds and installs are supported since R 4.2.0). It will report success if the installation of the architecture of the running R succeeded, whether or not the other architecture was successfully installed. The exceptions are packages with a non-empty configure.win script or which make use of src/Makefile.win. If configure.win does something appropriate to both architectures use[32](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#FOOT32) option --force-biarch: otherwise R CMD INSTALL --merge-multiarch can be applied to a source tarball to merge separate 32- and 64-bit installs. (This can only be applied to a tarball, and will only succeed if both installs succeed.)

If you have a package without compiled code and no Windows-specific help, you can zip up an installation on another OS and install from that zip file on Windows. However, such a package can be installed from the sources on Windows without any additional tools.
```

I don't understand what "to merge separate 32- and 64-bit installs" means, so I'm not feeling much clearer.

**Comment by paciorek** [comment]
@paul-vdb in case it's not clear, once you get binaries from Perry, we'd like you to:

1) install Nimble 1.0.0 binary from CRAN
2) install the nimbleHMC binary of interest from the file provided by Perry
3) run the tests in the `tests/testthat` directory

Let us know what happens for both binaries.

**Comment by perrydv** [comment]
It looks like --merge-multiarch is ignored. Here is what I have done so far (haven't sent binaries to Paul yet). See point 5.

0. Update nimbleHMC from GitHub
1. Install nimble from CRAN (confirmed it is 1.0.0)
2. `R CMD BUILD nimbleHMC`
3.  `R CMD INSTALL --install-tests --build nimbleHMC_0.1.0.tar.gz`
4.  `mv nimbleHMC_0.1.0.zip nimbleHMC_nomm_0.1.0.zip`
5.  `R CMD INSTALL --install-tests --merge-multiarch --build nimbleHMC_0.1.0.tar.gz`
    - **Output message**: `only one architecture so ignoring '--merge-multiarch'`

I will send both binaries to Paul, but it appears they might be identical.

**Comment by paciorek** [comment]
Ok, so that of course suggests we don't need to mention `--merge-multiarch` to CRAN. Perhaps not surprising since there is no compiled code in `nimbleHMC`, but we did have a user report about this, documented here:

```
I  would like to use the nimbleHMC package for sampling, but I could not install the package from the code:

remotes::install_github("nimble-dev/nimbleHMC", subdir = "nimbleHMC")


Downloading GitHub repo nimble-dev/nimbleHMC@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                          
2: CRAN packages only            
3: None                          
4: igraph (1.3.0 -> 1.3.5) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
igraph (1.3.0 -> 1.3.5) [CRAN]
Installing 1 packages: igraph
Warning: package ‘igraph’ is in use and will not be installed
v  checking for file 'C:\Users\n10677313\AppData\Local\Temp\Rtmpyerfzn\remotes5b1c7bd07847\nimble-dev-nimbleHMC-54453dc\nimbleHMC/DESCRIPTION' ...
-  preparing 'nimbleHMC':
v  checking DESCRIPTION meta-information ...
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'nimbleHMC_0.1.0.tar.gz'
   
Installing package into ‘C:/Users/n10677313/R/R-4.0.3/library’
(as ‘lib’ is unspecified)
* installing *source* package 'nimbleHMC' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'nimbleHMC'
    finding HTML links ... done
    addHMC                                  html  
    finding level-2 HTML links ... done

    buildHMC                                html  
    configureHMC                            html  
    nimbleHMC                               html  
    sampler_HMC                             html  
    sampler_langevin                        html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
Error : package 'nimble' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/n10677313/R/R-4.0.3/library/nimbleHMC'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/N10677~1/AppData/Local/Temp/Rtmpyerfzn/file5b1c75daba/nimbleHMC_0.1.0.tar.gz’ had non-zero exit status.
```

**Comment by paciorek** [comment]
Oh, jeesh, I confused things in this issue. For `nimble` we tell CRAN to use `--merge-multiarch`.

But the user pointed out to use that what is needed for `nimbleHMC` is `--no-multiarch` (and that is what we put in the r-nimble.org/ad-beta instructions):

```
devtools::install_github("nimble-dev/nimbleHMC", subdir = "nimbleHMC", INSTALL_opts=c("--no-multiarch"))
```

Sorry to confuse things here.

So I suppose if Paul's test is ok, maybe we don't need to ask CRAN to use `--no-multiarch`.

**Comment by paciorek** [comment]
So looking more at the user's error, I gather that the user had a 32-bit version of R but no 32-bit nimble, and so the failure there (when not using `--no-multiarch`) caused installation to fail.

I'm not sure what this suggests about whether building the Windows binary with `--no-multiarch` would make sense in terms of preventing failures for similar users.

I don't see much documentation about the `--no-multiarch` flag.

The `NEWS` for R 2.15.0 reports:

```
R CMD INSTALL for a package with compiled code will fail if compilation fails for any of the installed sub-architectures: use --no-multiarch to override this. 
```

Not sure if that's helpful for our understanding given we don't have compiled code in `nimbleHMC`. But I'm hoping that if users run into problems we can tell them to install the nimbleHMC binary with `--no-multiarch`. 

I suppose one additional thing would be for @perrydv  to try building nimbleHMC with `--no-multiarch` and seeing if the binary is any different.

**Comment by paciorek** [comment]
I think it's going to be identical to what you already built.

**Comment by perrydv** [comment]
Sounds good. Just following your suggestion above, if I understood it 😉

**Comment by danielturek** [comment]
@paciorek I think this is resolved, as we haven't heard about any such errors from users, or reported from @paul-vdb in the testing that was done.

Is this your understanding also?  If so, I would close this issue.
