### ISSUE TITLE
mis-spelling in alias for `sampler_NUTS`

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#38]
We need to fix "samspler" in the roxygen.

```
#' @aliases NUTS nuts HMC hmc samspler_NUTS
```

**Comment by danielturek** [comment]
@paciorek What branch are you looking at?

On `master` branch of `nimbleHMC`, line 692 appears to be:

```
#' @aliases NUTS nuts HMC hmc sampler_NUTS
```

**Comment by paciorek** [comment]
never mind - I was indeed on the wrong branch.
