### ISSUE TITLE
trap/warn if assign HMC to invalid nodes

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#40]
With the changes to AD handling, we are now in the position that a user could assign HMC to invalid nodes. For example, `dcat` and other discrete nodes or to nodes that have truncated or constraint dependencies.

At the moment we (as of `AD-stoch-ind` branching being merged into nimble`) simply have a run-time error when we run the HMC.

I think that in assigning NUTS samplers, we should check for invalid cases. I think these are:
 - discrete nodes
 - nodes assigned truncated distributions
 - nodes with dependencies of truncated distributions, `dinterval`, `dconstraint`
 - user-defined distribution without derivative support (I haven't thought through how difficult this would be)
 
@danielturek @perrydv  Thoughts?

**Comment by danielturek** [comment]
@paciorek Yes, I think that makes sense about the cases to catch.  In the HMC samplers we already were checking for discrete nodes, but not the other cases.

And @perrydv is there a way to determine if a user-defined distribution has AD support?

**Comment by danielturek** [comment]
Fixed in PR #42 and #57
