### ISSUE TITLE
clean up handling of HMC assigned to BNP model

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#43]
We get this non-ideal result if a user tries to unthinkingly apply an HMC sampler to a BNP model.

Note that `xi` nodes are discrete.

```
  code = nimbleCode({
    for(i in 1:100) {
        mu[i] ~ dnorm(mu0,sd=sigma)
        y[i] ~ dnorm(mu[xi[i]],1)
      }
    xi[1:100] ~ dCRP(conc=1, size=100)
  })

  y = rnorm(100)
  data = list(y=y)
  inits = list(xi = c(rep(1,50),rep(2,25),rep(3,25)), mu=rnorm(100))
  m = nimbleModel(code, data=data, inits= inits)
  conf <- configureHMC(m)
```

```
Error in addDefaultSampler(nodes = target, control = control, useConjugacy = useConjugacy,  : 
  Cannot determine wrapped sampler for cluster parameter mu[1]mu[2]mu[3]mu[4]mu[5]mu[6]mu[7]mu[8]mu[9]mu[10]mu[11]mu[12]mu[13]mu[14]mu[15]mu[16]mu[17]mu[18]mu[19]mu[20]mu[21]mu[22]mu[23]mu[24]mu[25]mu[26]mu[27]mu[28]mu[29]mu[30]mu[31]mu[32]mu[33]mu[34]mu[35]mu[36]mu[37]mu[38]mu[39]mu[40]mu[41]mu[42]mu[43]mu[44]mu[45]mu[46]mu[47]mu[48]mu[49]mu[50]mu[51]mu[52]mu[53]mu[54]mu[55]mu[56]mu[57]mu[58]mu[59]mu[60]mu[61]mu[62]mu[63]mu[64]mu[65]mu[66]mu[67]mu[68]mu[69]mu[70]mu[71]mu[72]mu[73]mu[74]mu[75]mu[76]mu[77]mu[78]mu[79]mu[80]mu[81]mu[82]mu[83]mu[84]mu[85]mu[86]mu[87]mu[88]mu[89]mu[90]mu[91]mu[92]mu[93]mu[94]mu[95]mu[96]mu[97]mu[98]mu[99]mu[100].
```

**Comment by danielturek** [comment]
@paciorek This traces to lines 490-491 of `MCMC_configuration.R`, specifically when trying to determine the nodes (and appropriate nested sampler) for the `CRP_cluster_wrapper` sampler.  This is failing, in this case when an HMC sampler is jointly sampling the cluster nodes (here, the `mu[i]`).  Here, the target of the HMC sampler is *all* cluster nodes, and hence belongs to all clusters, and the logic for adding a `cluster_wrapper` sampler does not handle this.

I could take a go at this, but I think it's something you might want to handle.  But let me know if I've looked too quickly.

**Comment by paciorek** [comment]
Point taken. I didn't look at all, so you're a step ahead of me. I will look into it.
