### ISSUE TITLE
Adding community guidelines

### ISSUE THREAD

**Issue by matt-graham** [nimble-dev/nimbleHMC#49]
Raising as part of JOSS review openjournals/joss-reviews/issues/6745

While I see [there are contributing guidelines on the main nimble repository ](https://github.com/nimble-dev/nimble/blob/devel/CONTRIBUTING.md), if contributors to nimbleHMC are advised to follow these for contributions to this specific package this should be explicitly stated, or better some specific contribution guidelines for this repository added.

Similarly it would be helpful to indicate where users should report issues (issue tracker on this repository or main nimbler repository, and when to choose which) and seek support more generally (for example linking to the [nimble-users Google group](https://groups.google.com/forum/?pli=1#!forum/nimble-users).

**Comment by danielturek** [comment]
@matt-graham Great suggestions again.

This is being addressed in PR #53

**Comment by danielturek** [comment]
@matt-graham PR #53 has been merged.

I'll leave it to you to review, and close this issue if you agree it's been addressed.

**Comment by matt-graham** [comment]
Thanks, this looks good to me so closing.
