### ISSUE TITLE
Adding installation instructions

### ISSUE THREAD

**Issue by matt-graham** [nimble-dev/nimbleHMC#50]
Raising as part of JOSS review

openjournals/joss-reviews/issues/6745

It would be useful to add some basic installation instructions to the top-level README similar to (and possibly building on / referring to) [those ](https://github.com/nimble-dev/nimble?tab=readme-ov-file#installation) inthe main nimble repository README

**Comment by danielturek** [comment]
@matt-graham It's a nice idea to give more detailed information about installation.

This is being addressed in PR #54

**Comment by danielturek** [comment]
@matt-graham PR #54 has been merged.

I'll leave it to you to review, and close this issue if you agree it's been addressed.

**Comment by matt-graham** [comment]
Thanks, #54 addresses the issue, closing.
