### ISSUE TITLE
Linking to API reference documentation on CRAN

### ISSUE THREAD

**Issue by matt-graham** [nimble-dev/nimbleHMC#51]
Raising as part of JOSS review openjournals/joss-reviews/issues/6745

This would perhaps be obvious to a regular R user, but it took me a while to find that [there is API documentation for the package available on CRAN](https://cran.r-project.org/web/packages/nimbleHMC/nimbleHMC.pdf). It would be useful to provide a pointer to this in the top-level README (and to the top-level CRAN entry https://cran.r-project.org/web/packages/nimbleHMC/).

**Comment by danielturek** [comment]
@matt-graham Yes, that's interesting.  Regular R users would be aware of this, but your experience is helpful to hear.

I've added links to this general package information (including the full package API) in PR #55.

**Comment by danielturek** [comment]
@matt-graham PR #55 has been merged.

I'll leave it to you to review, and close this issue if you agree it's been addressed.
