### ISSUE TITLE
mention `sampler_HMC` in `?samplers` in `ADoak`?

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#7]
@danielturek @perrydv  I'm wondering if the nimble package's `?samplers` should at least mention HMC and tell the user to run `?sampler_HMC` after loading `nimbleHMC` to get details. This would make the HMC sampler more easily discoverable.

**Comment by danielturek** [comment]
Sounds like a good idea.  @paciorek Would you like to add something, or prefer me to?  I only hesitate because I'm cautious to mess with the variety of `ADxxx` branches that now exist.

**Comment by paciorek** [comment]
I'll leave it to you. From Perry's email, it sounds like you can simply update ADoak.

**Comment by danielturek** [comment]
@paciorek Done, added brief information to branch `ADoak` of core `nimble`.
