### ISSUE TITLE
GH actions testing fails for Linux

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleHMC#8]
The linux test configurations fail at the time of (attempting) to install igraph, coda, nimble, etc.

**Comment by paciorek** [comment]
Looks like the issue is that the glpk system dependency of igraph is not installed. In `.github/workflows/ci.yaml` for `nimble` we have some invocations that cause the Ubuntu libgplk-dev package to be installed. I'll mimic those here in nimbleHMC...

**Comment by paciorek** [comment]
Looks ok now. @danielturek I'll let you modify `test.yaml` in terms of whether to run under Linux on all of `release`, `devel` and `oldrel-1`. For `nimble` we run on `release` and `devel`.

**Comment by danielturek** [comment]
@paciorek Thanks very much for trouble-shooting this.  I really appreciate.
